import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from '@/shared/components/ui/accordion'

export default function ImageToPromptFAQ() {
  const faqs = [
    {
      question: "How accurate is the image-to-prompt conversion?",
      answer: "Our AI achieves 95% accuracy in identifying key visual elements, artistic styles, and compositional details. The prompts are optimized for major AI platforms and consistently produce high-quality results that closely match your original image."
    },
    {
      question: "What image formats and sizes are supported?",
      answer: "We support all common formats including JPG, JPEG, PNG, WebP, and GIF. Images can be up to 10MB in size. For best results, we recommend high-resolution images (1024x1024 or larger) with clear subjects and good lighting."
    },
    {
      question: "Can I use the generated prompts commercially?",
      answer: "Yes! All prompts generated by our tool are free to use for personal and commercial projects. You own the rights to use these prompts in any AI art generator for client work, products, marketing materials, or any other commercial purpose."
    },
    {
      question: "Which AI art generators work with these prompts?",
      answer: "Our prompts are optimized for all major platforms including Midjourney, DALL-E 2/3, Stable Diffusion, Adobe Firefly, Leonardo AI, and many others. We provide platform-specific formatting options to ensure compatibility."
    },
    {
      question: "How long does it take to generate a prompt?",
      answer: "Prompt generation is almost instantaneous! Most images are analyzed and converted to detailed prompts within 2-5 seconds. Our AI processes images in real-time using advanced computer vision technology."
    },
    {
      question: "Can I edit or customize the generated prompts?",
      answer: "Absolutely! While our prompts are comprehensive, you can always edit, add, or remove elements to better suit your specific needs. The generated text serves as an excellent starting point that you can refine further."
    },
    {
      question: "Do you store my uploaded images?",
      answer: "We prioritize your privacy and security. Uploaded images are processed immediately and automatically deleted from our servers within 24 hours. We never store images permanently or use them for training our AI models."
    },
    {
      question: "Is there a limit to how many images I can process?",
      answer: "Free users can process up to 10 images per day. Premium subscribers get unlimited processing, batch upload capabilities, priority processing speeds, and access to advanced features like style transfer and prompt variations."
    },
    {
      question: "What makes this tool better than writing prompts manually?",
      answer: "Our AI captures subtle details that humans often miss, including precise color values, lighting conditions, artistic techniques, and composition elements. It can analyze and describe complex visual relationships in seconds, saving hours of manual work."
    },
    {
      question: "Can I process multiple images at once?",
      answer: "Premium users have access to batch processing, allowing you to upload and process multiple images simultaneously. This is perfect for large projects or when you need to generate prompts for entire image collections."
    }
  ]

  return (
    <section className="py-20 bg-white">
      <div className="container mx-auto px-4">
        <div className="text-center mb-16">
          <h2 className="text-4xl font-bold text-gray-900 mb-4">
            Frequently Asked Questions
          </h2>
          <p className="text-xl text-gray-600 max-w-2xl mx-auto">
            Everything you need to know about our image-to-prompt generator. 
            Can&apos;t find what you&apos;re looking for? Contact our support team.
          </p>
        </div>

        <div className="max-w-4xl mx-auto">
          <Accordion type="single" collapsible className="space-y-4">
            {faqs.map((faq, index) => (
              <AccordionItem key={index} value={`item-${index}`} className="border rounded-lg px-6">
                <AccordionTrigger className="text-left hover:no-underline py-6">
                  <span className="font-medium text-gray-900">{faq.question}</span>
                </AccordionTrigger>
                <AccordionContent className="text-gray-600 pb-6 leading-relaxed">
                  {faq.answer}
                </AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>
        </div>

        <div className="mt-16 text-center bg-gray-50 rounded-2xl p-8">
          <h3 className="text-2xl font-bold text-gray-900 mb-4">
            Still have questions?
          </h3>
          <p className="text-gray-600 mb-6">
            Our support team is here to help you get the most out of our image-to-prompt generator.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <button className="px-6 py-3 bg-purple-600 text-white rounded-lg hover:bg-purple-700 transition-colors">
              Contact Support
            </button>
            <button className="px-6 py-3 border border-gray-300 text-gray-700 rounded-lg hover:bg-gray-50 transition-colors">
              View Documentation
            </button>
          </div>
        </div>
      </div>
    </section>
  )
}